services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/app_home
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
volumes:
  postgres: {}
