default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: <%= ENV.fetch('POSTGRES_USER', 'finco') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>

development:
  <<: *default
  database: foundation_development

test:
  <<: *default
  database: foundation_test

production:
  <<: *default
  database: foundation_production
  username: foundation
  password: <%= ENV["FOUNDATION_DATABASE_PASSWORD"] %>
